# adjust challenge duration (seconds)
# set to -1 to set the time to infinite (players can only win by collecting every item and challenge starts on server startup)
challenge_duration: 5400

# spawn eggs, armor trims, candle cakes, potted items, banner patterns are disabled by default
# important: after adding/removing an item from excluded blocks, you need to delete the itemprogress.yml and restart your server
excluded_blocks:
  - CHAIN_COMMAND_BLOCK
  - COMMAND_BLOCK_MINECART
  - COMMAND_BLOCK
  - REPEATING_COMMAND_BLOCK
  - BEDROCK
  - AIR
  - FIRE
  - SOUL_FIRE
  - END_PORTAL_FRAME
  - NETHER_PORTAL
  - END_PORTAL
  - CHAINMAIL_HELMET
  - CHAINMAIL_LEGGINGS
  - CHAINMAIL_CHESTPLATE
  - CHAINMAIL_BOOTS
  - LIGHT
  - END_GATEWAY
  - DRAGON_EGG
  - TALL_SEAGRASS
  - VOID_AIR
  - PISTON_HEAD
  - MOVING_PISTON
  - WRITTEN_BOOK
  - DAMAGED_ANVIL
  - TORCHFLOWER_SEEDS
  - JIGSAW
  - TIPPED_ARROW
  - LAVA
  - WATER_CAULDRON
  - STRUCTURE_VOID
  - BARRIER
  - DEBUG_STICK
  - BUNDLE
  - FARMLAND
  - STRUCTURE_BLOCK
  - LAVA_CAULDRON
  - BUBBLE_COLUMN
  - CAVE_AIR
  - KNOWLEDGE_BOOK