name: ForceBattlePlugin
version: '4.5.0'
main: de.fameless.forceitemplugin.ForceBattlePlugin
api-version: '1.20'
author: fameless9
commands:
  timer:
  skipitem:
    aliases:
      - skip
  team:
  invite:
  backpack:
    aliases:
      - bp
  exclude:
  menu:
  reset:
  points:
