name: ForceItemPlugin
version: '3.1.0'
main: de.fameless.forceitemplugin.ForceItemPlugin
api-version: '1.20'
author: fameless9
commands:
  timer:
  skipitem:
    aliases:
      - skip
  team:
  invite:
  backpack:
    aliases:
      - bp
  exclude:
  menu:
